import "./globals.css";
import { Poppins } from "next/font/google";
import Header from '@/components/Header'

const poppins = Poppins({
  weight: ['400', '500', '600', '700'], subsets: ["latin"]
});

export const metadata = {
  title: "Rent",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <Header/>
        {children}
        footer
      </body>
    </html>
  );
}
